name: CI

on: [ push ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build the project
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-windows
          path: build/compose/binaries/main/msi/
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build the project
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-linux
          path: build/compose/binaries/main/
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build the project
        run: ./gradlew packageDistributionForCurrentOS
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-linux
          path: build/compose/binaries/main/